spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
     #   format_sql: true
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: create
  liquibase:
    enabled: false
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
logging:
  level:
    root: INFO
    #springfox.documentation.spring.web.readers.operation: DEBUG
    #org.apache.http.wire: DEBUG
    org.springframework.orm.jpa: TRACE
    org.hibernate.transaction: TRACE
    org.springframework.transaction: DEBUG
    #org.springframework.data: DEBUG
    org.hibernate.SQL:    DEBUG
    #org.hibernate.type: TRACE