spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://${MYSQL_HOST:localhost}/${MYSQL_DATABASE:vending-sys}?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${MYSQL_USER:vending-sys}
    password: ${MYSQL_PASSWORD:vendiNG2021@}
    initialization-mode: never
  jpa:
    #show-sql: true
    properties:
      hibernate:
        #   format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
logging:
  level:
    root: INFO
    #org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    #org.springframework.data: DEBUG
    #org.springframework.security: DEBUG
    #org.apache.http.wire: DEBUG
    org.hibernate.SQL:    DEBUG
    #org.hibernate.type: TRACE
